export const CHART_COLORS = {
  navy: 'var(--color-chart-1)',
  ocean: 'var(--color-chart-2)',
  navyDeep: 'var(--color-navy-deep)',
  sky: 'var(--color-sky)',
  textMuted: 'var(--color-text-muted-strong)',
  slate200: 'var(--color-slate-200)',
  slate100: 'var(--color-slate-100)',
  slate400: 'var(--color-slate-400)',
  slate500: 'var(--color-slate-500)',
  slate700: 'var(--color-slate-700)',
  white: 'var(--color-white)',
  slate500Alpha70: 'rgb(var(--color-chart-3-rgb) / 0.7)',
  slate500Alpha30: 'rgb(var(--color-chart-3-rgb) / 0.3)',
  slate700Alpha: (alpha) => `rgb(var(--color-chart-2-rgb) / ${alpha})`,
  navyAlpha05: 'rgb(var(--color-chart-1-rgb) / 0.05)',
  navyAlpha90: 'rgb(var(--color-chart-1-rgb) / 0.9)',
  navyAlpha95: 'rgb(var(--color-chart-1-rgb) / 0.95)',
  navyDeepAlpha04: 'rgb(var(--color-navy-deep-rgb) / 0.04)',
  navyDeepAlpha05: 'rgb(var(--color-navy-deep-rgb) / 0.05)',
  navyDeepAlpha08: 'rgb(var(--color-navy-deep-rgb) / 0.08)',
  navyDeepAlpha10: 'rgb(var(--color-navy-deep-rgb) / 0.1)',
  navyDeepAlpha20: 'rgb(var(--color-navy-deep-rgb) / 0.2)',
  navyDeepAlpha50: 'rgb(var(--color-navy-deep-rgb) / 0.5)',
  navyDeepAlpha80: 'rgb(var(--color-navy-deep-rgb) / 0.8)',
  navyDeepAlpha90: 'rgb(var(--color-navy-deep-rgb) / 0.9)',
  oceanAlpha10: 'rgb(var(--color-ocean-rgb) / 0.1)',
  oceanAlpha80: 'rgb(var(--color-ocean-rgb) / 0.8)',
  oceanAlpha100: 'rgb(var(--color-ocean-rgb) / 1)',
  skyAlpha08: 'rgb(var(--color-sky-rgb) / 0.08)',
  skyAlpha15: 'rgb(var(--color-sky-rgb) / 0.15)',
  skyAlpha20: 'rgb(var(--color-sky-rgb) / 0.2)',
  skyAlpha30: 'rgb(var(--color-sky-rgb) / 0.3)',
  redAlpha08: 'rgb(var(--color-red-rgb) / 0.08)',
  redAlpha12: 'rgb(var(--color-red-rgb) / 0.12)',
  redAlpha20: 'rgb(var(--color-red-rgb) / 0.2)',
  emeraldAlpha08: 'rgb(var(--color-emerald-rgb) / 0.08)',
  emeraldAlpha12: 'rgb(var(--color-emerald-rgb) / 0.12)',
  emeraldAlpha20: 'rgb(var(--color-emerald-rgb) / 0.2)',
};
